- hosts: all
  tasks:
  - name: setting up docker yum conf
    yum_repository: 
      name: dockername
      description: disc for docker 
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no

  - command: "sudo yum install docker-ce --nobest -y"   
  - pip:
     name: docker-py 
  - service:
      name: docker
      state: started 
    ignore_errors: yes
  - command: "sudo systemctl start docker"   
  - name: pull an image
    community.general.docker_image:
      name:  httpd
      state: present
      source: pull
    become: yes
  - name: create a data conrainer   
    community.general.docker_container:
      name: ans.web-ctnr8
      image: httpd
      ports: "3003:80"
      state: present
      restart: yes
      volumes: /home:/usr/local/apache2/htdocs
     
    become: yes
  - name: copy the file into the container
    copy: 
      src: /root/ansible_ws/index.html
      dest: /home       
    become: yes



          



