- hosts: 192.168.43.253
  vars_files: 
  - secinfo.yml
  tasks:
  - name: Sending an e-mail         
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ u }}"
      password: "{{ p }}"
      to: itsnios0108@gmail.com
      subject: Ansible-report
      body: 'resolved the mail-module challenge creating the vault'
  

